name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Restore Packages
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Lint Code
        run: npm run lint

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
